spring:
  application:
    name: gateway-demo
  cloud:
    gateway:
      routes:
        - id: between_route
          uri: http://www.baidu.com
          predicates:
            - Path=/baidu
            - Between=2023-02-26T13:00:00+08:00[Asia/Shanghai],2024-12-27T13:00:00+08:00[Asia/Shanghai]
        - id: header_route
          uri: http://www.baidu.com
          predicates:
            - Header=X-Request-id,\d+
        - id: host_route
          uri: http://www.baidu.com
          predicates:
            - Host=*.kim.com,{sub}.study.com
        - id: path_route
          uri: http://www.baidu.com
          predicates:
            - Path=/red/{segment},/blue/{segment}
        - id: weight_high
          uri: http://www.baidu.com
          predicates:

            - Weight=group1,5
        - id: weight_low
          uri: http://www.sogou.com
          predicates:
            #- Path=/weight
            - Weight=group2,5
logging:
  level:
    org.springframework.cloud: debug